name: Windows Release Package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=20 -DCMAKE_CXX_STANDARD_REQUIRED=ON -DCMAKE_CXX_EXTENSIONS=OFF -DCMAKE_CXX_FLAGS="/O2 /DNDEBUG /EHsc"
        cp LICENSE License.txt

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Release

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C Release

    - name: Package
      working-directory: ${{github.workspace}}/build/
      run: cpack

    - name: Archive Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: windows-2022
        path: |
          ${{github.workspace}}/build/sac-format.exe*
        retention-days: 1
