name: macOS 12

on:
  push:
    branches: ["devel"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3

    - name: Setup Clang 15.0.7
      run: |
        export CC=$(brew --prefix llvm@15)/bin/clang
        export CXX=$(brew --prefix llvm@15)/bin/clang++

    - name: Configure CMake
      run: cmake --preset gh-coverage

    - name: Build
      run: cmake --build ${{github.workspace}}/build/debug/gh-coverage

    - name: Test
      working-directory: ${{github.workspace}}/build/debug/gh-coverage
      run: ctest
