name: Windows 2022

on:
  push:
    branches: ["devel"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Configure CMake
      run: cmake --preset msvc-release

    - name: Build
      run: cmake --build ${{github.workspace}}/build/release/msvc

    - name: Test
      working-directory: ${{github.workspace}}/build/release/msvc
      run: ctest
