name: cpp-linter

on:
  push:
    branches: ["devel"]
  pull_request:
    branches: ["main"]

jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cpp-linter/cpp-linter-action@v2
        id: linter
        with:
          style: file
          version: 15
          files-changed-only: false
          extra-args: "-std=c++20"
          thread-comments: ${{ github.event_name == 'pull_request' && 'update' }}
