name: cpp-linter

on:
  push:
    branches: ["devel"]
  pull_request:
    branches: ["main"]

jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Make compile_commands.json
        run: |
          cmake --preset gh-coverage

      - name: cpp-lint
        uses: cpp-linter/cpp-linter-action@v2
        id: linter
        with:
          style: file
          version: 15
          files-changed-only: false
          ignore: "build/debug/gh-coverage/_deps | build/debug/gh-coverage/CMakeFiles | .github"
          extra-args: "-std=c++20 -p ./build/debug/gh-coverage/compile_commands.json"
          thread-comments: ${{ github.event_name == 'pull_request' && 'update' }}
